---
- name: enable the codeready repository
  rhsm_repository:
    name: codeready-builder-for-rhel-8-x86_64-rpms
    state: enabled

- name: install required packages
  yum:
    name:
      - diffutils
      - file-devel
      - gcc
      - jansson-devel
      - make
      - nss-devel
      - libyaml-devel
      - libcap-ng-devel
      - libpcap-devel
      - pcre-devel
      - python3
      - python3-pyyaml
      - rust-toolset
      - zlib-devel
    state: present

- name: create suricata directory
  file:
    path: "~/suricata"
    state: directory

- name: download suricata
  get_url:
    url: "https://www.openinfosecfoundation.org/download/suricata-{{ current_version }}.tar.gz"
    dest: "~/suricata/suricata-{{ current_version }}.tar.gz"

- name: untar the suricata archive
  unarchive:
    src: "~/suricata/suricata-{{ current_version }}.tar.gz"
    dest: "~/suricata"
    remote_src: true

- name: run the configure command
  shell: "~/suricata/suricata-{{ current_version }}/configure --sysconfdir=/etc --localstatedir=/var"
  args:
    creates: "~/suricata/suricata-{{ current_version }}/config.status"

- name: run the make command
  make:
    chdir: "~/suricata/suricata-{{ current_version }}"

- name: run the make install command
  make:
    chdir: "~/suricata/suricata-{{ current_version }}"
    target: install