---
- name: download epel repository package
  get_url:
    url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    dest: "~/"

- name: install epel repo
  shell: "rpm -ivh ~/epel-release-latest-7.noarch.rpm"
    creates: /etc/yum.repos.d/epel.repo

- name: install suricata
  yum:
    name: suricata
    state: present