---
# tasks file for suricata_update
- name: "[INCLUDE TASK] - suricata config"
  include_tasks: suricata_config.yml
  when: suricata_config | bool | default('false')

- name: run the update
  shell: suricata-update -c /etc/suricata/update.yaml
  register: update_results

- name: debug update results
  debug:
    var: update_results