---
# tasks file for suricata_update
- name: first configure update
  copy:
    src: update.yaml
    dest: /etc/suricata/update.yaml
    mode: "0640"
    owner: suricata
    group: suricata

- name: run the update
  shell: suricata-update -c /etc/suricata/update.yaml