---
# tasks file for suricata_update
- name: "[INCLUDE TASK] - suricata config"
  include_tasks: suricata_config.yml
  when: suricata_config | bool


- name: "[INCLUDE TASK] - suricata update"
  include_tasks: suricata_update.yml
  when: suricata_update | bool


- name: "[INCLUDE TASK] - suricata push"
  include_tasks: suricata_push.yml
  when: suricata_push | bool

- name: "[INCLUDE TASK] - suricata validate"
  include_tasks: suricata_validate.yml
  when: suricata_validate | bool

