---
- name: fetch the rules from the suricata admin server
  fetch:
    src: "{{ suricata_dir }}/suricata.rules"
    dest: "{{ role_path }}/files/"
    flat: true
    mode: "0644"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  delegate_to: "{{ suricata_admin_server }}"
  run_once: true

- name: push the rules to the clients
  copy:
    src: "{{ role_path }}/files/suricata.rules"
    dest: "{{ suricata_dir }}/suricata.rules"
    mode: "0644"
    backup: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  register: rulepush_results
  when: inventory_hostname != suricata_admin_server
  notify:
    - Restart Suricata

- name: debug the results
  debug:
    var: rulepush_results
  when:
    - rulepush_results is defined and rulepush_results.changed | bool

- name: Force handlers
  meta: flush_handlers