---
- name: first configure update yaml file i.e. /etc/suricata/update.yaml
  copy:
    src: update.yaml
    dest: /etc/suricata/update.yaml
    mode: "0640"
    owner: suricata
    group: suricata
  delegate_to: "{{ suricata_admin_server }}"
  run_once: true

- name: check for line in systemd service file
  shell: 'grep "\-\-init\-errors\-fatal" {{ suricata_service_file }}'
  register: shell_result
  ignore_errors: true
  failed_when: false

- name: replace line in systemd service file
  lineinfile:
    dest: /root/testfile
    state: present
    regexp: '^(ExecStart=.* (?!{{ init_fail }}))'
    backrefs: true
    backup: true
    line: '\1{{ init_fail }}'
  vars:
    init_fail: "--init-errors-fatal"
  when: shell_result.rc == 1

- name: ensure that the suricata service is running
  systemd:
    name: suricata
    state: restarted
    enabled: true
    daemon-reload: true