---
- name: run the update
  shell: suricata-update -c /etc/suricata/update.yaml
  register: update_results
  delegate_to: "{{ suricata_admin_server }}"
  run_once: true

- name: debug update results
  debug:
    var: update_results
  delegate_to: "{{ suricata_admin_server }}"
  run_once: true