---
- name: get service facts
  service_facts:
  register: services_result

- name: debug service facts
  debug:
    var: services_result.ansible_facts.services

- name: set fact
  set_fact:
    service_state: "{{ services_result.ansible_facts.services }}"

- name: set fact 2
  set_fact:
    suricata_state: "{{ service_state['suricata.service'] }}"

- name: fail if the service is not running
  fail:
    msg: "The Suricata service is not running.  There may be an issue with updated rules file"
  when: suricata_state.state == "stopped"