---
- name: get service facts
  service_facts:
  register: services_result

- name: debug service facts
  debug:
    var: services_result.ansible_facts.services

- name: fail if the service is not running
  fail:
    msg: "The Suricata service is not running.  There may be an issue with updated rules file"
  when: services_result.ansible_facts.services.['suricata.service'].state == "stopped"